AUTO_UPDATE_TIME = 20

SERVER_INVITE = ""
BOT_INVITE = ""
GITHUB_LINK = ""

ADMIN_PRIVILEGE_ROLES = ['Admin', 'Moderator', 'Lockout Manager']
OWNERS = [195237189582323712]

BACKUP_DIR = "./data/backup/"


